name: Build & Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-and-release-linux-appimage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev patchelf

      - name: setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install the CLI tool
        run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'
        
      - name: flutter_rust_bridge_codegen
        run: flutter_rust_bridge_codegen generate

      - name: flutter pub get
        run: flutter pub get

      - name: build linux
        run: |  

          sudo apt install -y libfuse2
          
          curl -JOL https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool

          flutter build linux --release
          
          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_video_plugin.so
          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_native_event_loop.so
          
          mv build/linux/x64/release/bundle/{mangayomi,AppRun}
          cp linux/appimage/* build/linux/x64/release/bundle/
          ./appimagetool build/linux/x64/release/bundle/
          mv *.AppImage build/Mangayomi-${{ github.ref_name }}-linux.AppImage

      - name: upload artifact linux appimage
        uses: actions/upload-artifact@v3
        with:
          path: build/Mangayomi-*.AppImage
      - name: Rrelease packages appimage
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/Mangayomi-*.AppImage
          allowUpdates: true